### ISSUE TITLE
.netstandard compatibility issue

### ISSUE THREAD

**Issue by jackbond** [micjahn/ZXing.Net#100]
I'm getting an exception while migrating a utility project which uses ZXing from full framework to .netstandard. The problem occurs when I try to instantiate a class derived from BarcodeReader<T>. I get the following exception

Could not load type 'ZXing.Func`2' from assembly 'zxing, Version=0.16.2.0, Culture=neutral, PublicKeyToken=4e88037ac681fe60'.

I've attached a minimal VS2017 solution which demonstrates the problem. The unit test GenerateQrSuccess creates a qr code and then raises an exception when attempting to decode it.

[standardissue.zip](https://github.com/micjahn/ZXing.Net/files/1885571/standardissue.zip)

**Comment by micjahn** [comment]
There are issues with nuget and the packages. The references are mixed up from different targets.
If you manually copy zxing.dll, zxing.magick.dll and Magick.NET-Q8-AnyCPU.dll from the same target directory to the build directory the test works.
Perhaps the solutions from the following issue would help in your case:
https://github.com/Redth/ZXing.Net.Mobile/issues/578
(<PackageTargetFallback> or <AssetTargetFallback>)
Otherwise you have to wait for the next release of zxing.net which has .net standard 2.0 support.

**Comment by irowbin** [comment]
@jackbond  I am not getting any issues on `dotnet core 2.0` by using `XZing` & `Install-Package ZXing.Net.Bindings.ImageSharp -Version 0.16.4-beta`.  I can share my code snippet.

**Comment by micjahn** [comment]
The nuget package for the ImageSharp binding has only .Net Standard assemblies. The Magick package contains assemblies for .Net Framework 2.0 and 4.0.
