### ISSUE TITLE
Using zxing to scan qr code from Iphone Wallet

### ISSUE THREAD

**Issue by amitkaushal80** [micjahn/ZXing.Net#107]
I am using zxing in my project to scan qr code from Wallet. And my project is working fine. Thank for the this perfect solution. 
My issue is that as soon as i scan the qr code my scanner light got off even i keep pressing the scanner button. Is there any functionality available with the help of which if the keep the scanner button pressed i can scan different code. 
I need this functionality because My application is like a kiosk, which facilitates different user to scan their QR code from there wallet and get the desired information. I dont want the client to hold the scanner and press the button and scan. Instead they just come and scan without even touching the scanner.

**Comment by micjahn** [comment]
I think you talk about a different project which is based on ZXing.Net.
https://github.com/Redth/ZXing.Net.Mobile
Because ZXing.Net itself doesn't provide any special functionality for different mobile platforms. It's only a general library which can decode barcodes from images. So I can't help you with your question.
