### ISSUE TITLE
Can't decode QR code generated by ZXing

### ISSUE THREAD

**Issue by snoward** [micjahn/ZXing.Net#109]
Hi! 

I have tested how ZXing works on images with multiple qr codes and found an interesting case

1) Encode some data to QR code
2) Place it on white background
3) Recognize it in two modes: `Decode` and `DecodeMultiple`
first mode returns null, second - correct data

Images sources: https://yadi.sk/d/BoHHVIZk3WRDaS
```
reader = new BarcodeReader
 {
     Options = { PossibleFormats = new[] { BarcodeFormat.QR_CODE }, TryHarder = true }
 };

// returns null
var qrCode = reader.Decode(image);

//returns result with decoded text
var qrCodes = reader.DecodeMultiple(image);
```
![qr-1](https://user-images.githubusercontent.com/8896921/40444503-fb070022-5ee2-11e8-993c-69f85b21e69a.png)

**Comment by micjahn** [comment]
That's a very special case.
ZXing looks for the corners markers of qr codes. In your case it finds four of them but they are not from the same code. Every corner marker is from another one of the four qr code because you aligned them in a square. I don't see the chance to fix it because it is a generated image which normally doesn't exists in that form.
DecodeMultiple splits the image in different regions which are scanned independently.
