### ISSUE TITLE
how to simplify hex string

### ISSUE THREAD

**Issue by zhuyangping** [micjahn/ZXing.Net#115]
Hi 
Is there a way to convert QR Code into a simplified hex string?

**Comment by micjahn** [comment]
What do you mean? Do you want to convert the generate barcode image to hex or something different?

**Comment by micjahn** [comment]
That question is a little bit out of scope of that project here. It's better to ask it on platforms like stack overflow: https://stackoverflow.com/search?q=c%23+image+hex

In the past I did something similar but instead of hex I converted the image to base64:
https://github.com/micjahn/ZXing.Net/blob/master/Clients/ASP.NetCoreDemo/Helper/BarcodeTagHelper.cs
(method: GeneratePng)
