### ISSUE TITLE
Xamarin iOS: barcode scanning reading wrong barcodes

### ISSUE THREAD

**Issue by ankiitbansal** [micjahn/ZXing.Net#123]
In Xamarin iOS, we have set tryharder option as true, using the Landscape mode for scanning, API is returning  sometimes wrong barcode value. Moreover if we point camera to any printed graphic having lines it scan that as well.

Types of barcode returned when pointed towards fabric having strips/straight lines or texture : MSI UPC_E

**Comment by micjahn** [comment]
Not sure if you are using ZXing.Net or ZXing.Net.Mobile. If you are using ZXing.Net.Mobile you should open an issue here: https://github.com/Redth/ZXing.Net.Mobile
MSI isn't enabled by default because it is known to produce to many false positives.
You should remove it from the initialization of your barcode reader instance (BarcodeReader -> Options -> PossibleFormats).
