### ISSUE TITLE
Data Matrix  - using zxing.dll Interop VB Script  (Margin Issue)

### ISSUE THREAD

**Issue by ClassicDude** [micjahn/ZXing.Net#125]
I just want to point out regarding data matrix - there is issue with 'margin' size for the output image.

here is the code I've used:

  qrCodeOptions.Height = 35
  qrCodeOptions.Width = 35
  qrCodeOptions.Margin = 0
  qrCodeOptions.PureBarcode = True
  qrCodeOptions.DefaultEncodation = ZXing.Datamatrix.Encoder.Encodation.ASCII
  qrCodeOptions.SymbolShape = ZXing.Datamatrix.Encoder.SymbolShapeHint.FORCE_SQUARE

As you can see below images:

This is original image size: 

![datamatrix_4a7-c30-024-805](https://user-images.githubusercontent.com/41024771/42995244-44b8f5fc-8c08-11e8-83c3-0fc19717a187.png)

This isn't right size - margin become bigger and data matrix become much smaller why?

![datamatrix_3ae-d0d-e41-fb5](https://user-images.githubusercontent.com/41024771/42995243-44a080c6-8c08-11e8-99e1-94f7afba4f0c.png)

for your information: both data come in random alphanumeric as 15 char max

**Comment by micjahn** [comment]
The option "margin" only works in all cases if you give the value 1 for "height" and "width". The second data matrix code needs more codewords than the first one. For the first code the generator needs a width and height of 16 pixel. That is stretched to 32x32 because you give a dimension of 35x35. 32x32 is the nearest size which can be created from the original size of 16x16 without anti-aliasing (which isn't supported by the renderer). The resulting image has a border of 1 pixel at the top and left and 2 pixel at the bottom and right.
The second datamatrix needs 18x18 pixels to represent your data. That size can't be stretched by 2 because it would be greater that 35x35.
