### ISSUE TITLE
Unable to run  CommandLineEncoder console application with .net core configuration and release mode

### ISSUE THREAD

**Issue by pranavdhundhia** [micjahn/ZXing.Net#169]
I am trying to configure CommandLineEncoder project with .net cor e and Release mode . Trying to run project in release mode gives me error . Unable to load ZXing.Net 0.16.4 with assembly reference. 

Please let me know configuration to run BarcodeGenretor with CommandLineEncoder with .net core setup

**Comment by pranavdhundhia** [comment]
Please find project file. I do have attached txt file of project in following zip.
Thanks a lot for your response
[CommandLineEncodertxt.zip](https://github.com/micjahn/ZXing.Net/files/2801881/CommandLineEncodertxt.zip)

**Comment by micjahn** [comment]
You have to create a completely new project file. You can't use the existing one. The current command line encoder uses the Bitmap class from the full framework. As far as I know with .net core you have to use an additional image library because .net core doesn't contain the necessary Bitmap implementation.
The smallest possible project file with VS2017 should be:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ZXing.Net" Version="0.16.4" />
    <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.6" />
  </ItemGroup>

</Project>```
This one uses the Windows Compatibility pack because of the missing Bitmap class.
After creating the new console project you have to copy the content from the file Program.cs of the original project to your newly created one. Fix the 1 or 2 compile errors and you should work as expected.

**Comment by pranavdhundhia** [comment]
Michael, thank you for your kind reply and for your advice. As per your advice I do have created new console project and added  ZXing.Net.Bindings.CoreCompat.System.Drawing  with .net core as an additional image library for bar-code generation. Now it works with .net core support without compatibility pack . Thanks
