### ISSUE TITLE
How to force numeric QR code

### ISSUE THREAD

**Issue by movedoa** [micjahn/ZXing.Net#17]
I tried to generate a simple numeric QR code with the content "123456".

But when i decode the generated qr code on https://zxing.org/w/decode.jspx it says that is is type text.
I just use the write method here.
Is there a way to force a numeric QR code?

**Comment by movedoa** [comment]
Nervermind, the reader is just bad :P

**Comment by movedoa** [comment]
https://zxing.org/w/decode.jspx also says the type of the qr code is text

**Comment by micjahn** [comment]
You can't manually select the mode how the content should be encoded. The character 0x0A is added by the online reader page. If you decode the image with ZXing.Net you won't get it. I tried the complete encoding-decoding cycle with your content and everything works fine. Internally the encoding algorithm selected the NUMERIC encoding mode because there are only numbers. I checked it twice. The output "Parsed Result Type" = "TEXT" doesn't mean that the content is encode in ALPHANUMERIC mode. It only says, that the result contains unformatted text. Other types are vEvent, vCard, Calendar, SMS and so on. That information is from the class ZXing.Client.Result.ResultParser.
