### ISSUE TITLE
ZXing.CoreCompat.System.Drawing and VS 2017

### ISSUE THREAD

**Issue by cyberh0me** [micjahn/ZXing.Net#20]
FYI [An internal error occurred. Please contact Microsoft Product Support Services.](https://developercommunity.visualstudio.com/content/problem/62421/an-internal-error-occurred-please-contact-microsof.html)

basically i need to show QRCode (.NETCoreApp 1.1) and thought the ASP.NetCoreDemo is a good start but it requires ZXing.CoreCompat.System.Drawing 

is there any other possibility to display a QRCode without ZXing.CoreCompat.System.Drawing ?

**Comment by micjahn** [comment]
With v0.15.0 there are only two renderes available, SVG and pixel data (raw data, BGRA). Next version provides different bindings for other imaging libraries as separate NuGet packages. At the moment you can find them in the source code repository under the path Source/adapters.
Do you miss something?

**Comment by cyberh0me** [comment]
i have missed working samples and good documentation but meanwhile i was able to produce what i needed but i am not happy to use ZXing.CoreCompat.System.Drawing which uses the same namespace like some Microsoft libraries and i love to see no error messages if i open the source...

**Comment by micjahn** [comment]
I'm not sure what you mean. All samples are working. A good documentation is missing, that's true. You don't have to use CoreCompat.System.Drawing (it's not a ZXing library, it's a third party component because ASP.Net Core doesn't contain image classes (https://github.com/CoreCompat/CoreCompat)). I can't influence the namespace. 
You can use any other imaging library which is available for ASP.Net Core. For some of them there are ready-to-use extensions in the repository available.
And if you mean with "... love to see no error messages ..." that you open the VS2015 solution/project with VS2017 and it throws an error, what should I say, I can't guarantee that every hard work of mine, which I provide for free and which is built with VS2015, will work in the future with VS2017, VS2018, VS2019...

**Comment by kaburkett** [comment]
what you really should say is 'if you want to create a pull request with a fix for vs2017 I will review and merge'
