### ISSUE TITLE
simple C# code example for barcode reader including it's refrences

### ISSUE THREAD

**Issue by ellLazar** [micjahn/ZXing.Net#24]
help,
need :
simple C# code example for barcode reader from file(.tif , .png , .pdf) including it's references (.dll)
what exactly .dll's needed to refrence, and from what directory to copy

one page class.cs will help .

regards,
EL

**Comment by micjahn** [comment]
You can find a really simple sample at the project home page:
https://github.com/micjahn/ZXing.Net
Scroll a little bit down until you see the section "Usage examples".
You can download the assemblies from the release section
https://github.com/micjahn/ZXing.Net/releases
or via nuget.
The specific build which you have to use depends on the project which you want to build.
In most case nuget will do the job for you.

**Comment by ellLazar** [comment]
hello micjahn,
thanks for answer.

1.
bercode decode code_39

I made some testing with the ZXing barcode reader,
I realize that in many cases it's not so accurate.
I made some comparison with other's professional barcode reader
and I found that ZXing give some less results.
 are there some settings options I can add to make better results ?
are there some limits to barcode size (width too long about 13 numric char's ?) 

2. if I have more than one barcode in page how I can get all barcodes in array or delimited string  ?

thanks,
EL

**Comment by micjahn** [comment]
I doesn't know your environment but I will try to give some hints.
Every possible option is accessible through the class DecodingOptions which is behind the property Options of the barcode reader class. There are some options for CODE 39. You should play around with this and find the setting which works best for you. The DecodingOptions also contains a property TryHarder which you should set to true if CPU cycle count doesn't matter.
Another important thing is the quality of the image. If you develop an app for a mobile phone you shouldn't use the highest possible resolution of the webcam. Something around 1024x1024 pixels are enough in most cases because the user holds the phone near to the code.
If you develop a desktop app which, for example, reads barcodes from scanned image you have to try out
which resolution gives the best results. Important note don't use the black and white mode of the scanner. Scan it as colored or grayscale image.

For multiple barcodes use the method DecodeMultiple. But ZXing doesn't guarantee that it will find every single barcode on a page.

**Comment by ellLazar** [comment]
thanks for detailed answer

TryHarder
is in #C VS2015 that it has an exception, I cannot use this option.

is it possible to "help" the decoder, to find only numeric digits(0,1,2,3...,9) ?
may be something charset ?
how to use charset ?

**Comment by micjahn** [comment]
What exception do you get with TryHarder?

What do you want to try with "only numbers"? The reader looks for a appropriate barcode and tries to
decode the content. There is no charset or similar for CODE 39.

And as I said before if possible use grayscale images instead of black&white.

**Comment by ellLazar** [comment]
ZXing accuracy,
I tried ZXing vs 3 others barcode engines , 
in most cases the results where good, but  fond some barcodes that where looking good, that ZXing could not recognize them (but  other engines succeed to recgonize),
what is the reason for that ?,
with adding some other settings can help or this is the limit of ZXing ?
at last I succeed to the  .options.tryharder =true also, but it did not help.

EMGUcv
I noticed you are using emguCV, for what purpose you use this library ?

**Comment by micjahn** [comment]
EmguCV and other imaging libraries are only used by the demo implementations to show how it works. ZXing.Net itself has no dependencies to 3rd party libraries.

Accuracy: ZXing.Net doesn't guarantee that it will find every barcode. Other engines using different algorithms which are better in some circumstances. Feel free to provide a PR which enhance the quality of the scanning process. There are no other options like TryHarder which can be used.
