### ISSUE TITLE
Blazor Web Assembly Error

### ISSUE THREAD

**Issue by patled** [micjahn/ZXing.Net#273]
I got an issue at runtime when scanning a barcode in a Blazor WebAssembly project:

System.TypeInitializationException: The type initializer for 'System.Drawing.GDIPlus' threw an exception. ---> System.DllNotFoundException: libc assembly:<unknown assembly> type:<unknown type> member:(null) at (wrapper managed-to-native) System.Drawing.GDIPlus.uname(intptr) at System.Drawing.GDIPlus..cctor () <0x2f77648 + 0x000a4> in <filename unknown>:0

I'm pretty stuck here. Any ideas?

I published the project under 
https://github.com/patled/wasm-barcodescanner

Thanks in advance!

**Comment by micjahn** [comment]
In my opinion the target system is missing some libraries which are needed for the System.Drawing assembly. Doesn't look like a native zxing.net problem.
Which platform is the target system? (Linux, AWS, Windows, ...) ZXing.Net provide assembly versions compiled for different platforms like .net framework, .net core and standard, etc. Which one do you use?

**Comment by patled** [comment]
The project runs under Windows 10 / NETStandard-Libary 2.1.0

**Comment by micjahn** [comment]
Ok, I know what happens but I have no solution. Perhaps you shouldn't use CoreCompat.
The problem exists inside the CoreCompat assembly CoreCompat.System.Drawing.dll. 
The constructor of the type System.Drawing.GDIPlus is called. The following code is executed:
```
        int platform = (int)Environment.OSVersion.Platform;
	if (platform == 4 || platform == 6 || platform == 128)
	{
		if (Environment.GetEnvironmentVariable("not_supported_MONO_MWF_USE_NEW_X11_BACKEND") != null || Environment.GetEnvironmentVariable("MONO_MWF_MAC_FORCE_X11") != null)
		{
			UseX11Drawable = true;
		}
		else
		{
			IntPtr intPtr = Marshal.AllocHGlobal(8192);
			if (uname(intPtr) != 0)
			{
				UseX11Drawable = true;
			}
			else if (Marshal.PtrToStringAnsi(intPtr) == "Darwin")
			{
				UseCarbonDrawable = true;
			}
			else
			{
				UseX11Drawable = true;
			}
			Marshal.FreeHGlobal(intPtr);
		}
	}
```

The WASM environment gives the value 4 for the property Environment.OSVersion.Platform. The value 4 means "Unix".
If you follow the execution path the following code is executed because of the value 4 for the platform:
`if (uname(intPtr) != 0)`
The method 'uname' is an external declaration which is only available on unix platforms in the library libc. Here is the extern declaration within the CoreCompat assembly:
```
[DllImport("libc")]
private static extern int uname(IntPtr buf);
```

You can use another library for image processing which works perhaps better within WASM.
Or you find a way to manipulate the Environment.OSVersion.Platform, perhaps with reflection.

It is not fixable within the ZXing assemblies.

**Comment by realivanjx** [comment]
@micjahn Why not use `RuntimeInformation.IsOSPlatform` instead of calling external library and dealing with pointers?

**Comment by gkenaston** [comment]
@patled Did you get this to work in Blazor WASM?

**Comment by micjahn** [comment]
@realivanjx The code snippet is from a different project: CoreCompat.System.Drawing.dll
ZXing.Net isn't using pointers at all.

**Comment by patled** [comment]
> @patled Did you get this to work in Blazor WASM?

@gkenaston No, I couldn't get it running in Blazor WASM :(

**Comment by sabitertan** [comment]
@gkenaston , @patled 
I was able to use ZXing.Net in wasm project with ImageSharp.
https://github.com/sabitertan/BlazorWasmBarcodeScanZxingNet
