### ISSUE TITLE
Decode method returns null

### ISSUE THREAD

**Issue by programmersharp** [micjahn/ZXing.Net#311]
I am trying to decode the qr code using QRCodeReader and BarcodeReader with different options, but Decode returns null for them. I attached the pdf file and just the image from this pdf. Any advise?

[1QR Scan.pdf](https://github.com/micjahn/ZXing.Net/files/6000767/1QR.Scan.pdf)
![img](https://user-images.githubusercontent.com/2078015/108317432-5600e400-71cf-11eb-83f7-d8027c5c2d74.png)

**Comment by Iijialtd** [comment]
I would also like to know if there is this solution. Previously, when I scanned an invoice with a QR code once, made it into a PDF file, and read the QR code of that file in the library, there was a high probability that it failed to read. I know that the cause is that the dots of the QR code are blurred in the grayscale mode during scanning. You can print the paper once and read it with the QR code reading application on your smartphone without any problems. When the QR code of this attached PDF is also enlarged, the dots are blurred, so it cannot be read by normal library reading. I thought that the reading rate would increase if there was a technology to see the image data from a distance, but at that time I could not find it and gave up.

**Comment by micjahn** [comment]
I think it isn't decoded because some edges are blurry and the modul size for the upper right and the lower left position marker isn't consistent. I have no hint for you which you can do to improve the decoding process. Sorry.
