### ISSUE TITLE
Image doesn't parse QR Code

### ISSUE THREAD

**Issue by bobjase** [micjahn/ZXing.Net#36]
The attached image doesn't successfully read the QR code, even though the identical image has no problem at https://zxing.org/w/decode.jspx
![sampleqr4](https://user-images.githubusercontent.com/25090541/29569277-017c3714-8721-11e7-882d-65b5451560d6.jpg)

**Comment by micjahn** [comment]
I don't know what you have tried but for me it works.
It is important to know, what the java online decoder does in the background. As far as I know it uses the GlobalHistogramBinarizer instead of the HybridBinarizer (or both, not sure) which is used as default in ZXing.Net BarcodeReader class. If the BarcodeReader class uses the GlobalHistogramBinarizer too it will find both codes in the picture.
The main problem is that the HybridBinarizer gives better results for other pictures. If you want the best out of zxing you have to decode a picture twice, once with every binarizer. But it slows down the decoding speed.
So the default for ZXing.Net is the HybridBinarizer. If you have enough CPU cycles free in your target environment you can enhanced the decoding and try to find the codes with both binarizers.

**Comment by bobjase** [comment]
Thanks for getting back to me.

I downloaded ZXing.Net.Master and built the winForms demo.

There is no combination of setting that will get this to read the QR code (though it does read the barcode).

How do I specify the binarizer?

**Comment by bobjase** [comment]
I just changed the code from
```

private static readonly Func<LuminanceSource, Binarizer> defaultCreateBinarizer =
         (luminanceSource) => new HybridBinarizer(luminanceSource);
```

to

```
private static readonly Func<LuminanceSource, Binarizer> defaultCreateBinarizer =
         (luminanceSource) => new GlobalHistogramBinarizer(luminanceSource);
```
and it still did not work

**Comment by micjahn** [comment]
You have to enable the option for multiple barcodes.

**Comment by bobjase** [comment]
it's enabled

**Comment by bobjase** [comment]
https://www.screencast.com/t/Z9S71oAzAC

**Comment by bobjase** [comment]
I tried toggling "only find QR" - still no luck

**Comment by micjahn** [comment]
I do exactly the same and it works. Crazy. Scratching my head.
Are you sure that the project is build correctly after your changes?

**Comment by bobjase** [comment]
I did a clean and rebuild. Same issue

**Comment by micjahn** [comment]
Can you please try out the attached binary build of the WinForms demo?
The ZIP-Archiv includes the picture from this issue, too.
[WindowsFormsDemo_GlobalHistogramBinarizer.zip](https://github.com/micjahn/ZXing.Net/files/1261374/WindowsFormsDemo_GlobalHistogramBinarizer.zip)
