### ISSUE TITLE
How to use BarcodeWriter in netstandard2.1

### ISSUE THREAD

**Issue by Edward-Zhou** [micjahn/ZXing.Net#370]
I am trying to create qrcode with ZXing.net in netstandard2.1.

I got error with below code:
```
    public class QRCode
    {
        public void Create(string content)
        {
            var options = new QrCodeEncodingOptions
            {
                DisableECI = true,
                CharacterSet = "UTF-8",
                Width = 250,
                Height = 250,
            };
            var writer = new BarcodeWriter();
            writer.Format = BarcodeFormat.QR_CODE;
            writer.Options = options;
        }
    }
```

It throws **Using the generic type 'BarcodeWriter<TOutput>' requires 1 type arguments**

I added ZXing.Net package, is there any other reference I need to add?

**Comment by micjahn** [comment]
If you use ZXing.Net with .Net Standard you have to add one additional package with a specific implementation of the barcode reader and writer classes for the image manipulation library you want to use.
https://www.nuget.org/packages?q=ZXing.Net.Bindings*
That's because .net standard doesn't include System.Drawing by default.

For example you can add the following package:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
A small change in your code is necessary to use the specific BarcodeWriter class:
```
    public class QRCode
    {
        public void Create(string content)
        {
            var options = new QrCodeEncodingOptions
            {
                DisableECI = true,
                CharacterSet = "UTF-8",
                Width = 250,
                Height = 250,
            };
            var writer = new ZXing.Windows.Compatibility.BarcodeWriter();
            writer.Format = BarcodeFormat.QR_CODE;
            writer.Options = options;
        }
    }
```
