### ISSUE TITLE
Compilation fails wih missing classes upgrading from 16.6 to 16.7 

### ISSUE THREAD

**Issue by oduis** [micjahn/ZXing.Net#378]
When I upgrade my .Net Core 6 project via nuget to 16.7, many classes cannot be found any more, e.g. BitmapLuminanceSource or BarcodeReader constructor without parameters.
Had to downgrade to 16.6 to make the code compile again.

**Comment by micjahn** [comment]
Please use the following nuget package:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/

Background:
ZXing.Net 0.16.7 contains an assembly which is build against .Net 6.0.
But that version doesn't contain the bitmap support. That is necessary because otherwise the assembly can't be used
on platforms which doesn't support System.Drawing (f.e. WASM/Webassembly).
Before 0.16.7 the .Net Coreapp 3.1 version of ZXing.Net is added to your project by nuget which has bitmap support builtin.

Now you have the option to use ZXing.Net for .Net 6.0 with System.Drawing or every other supported image manipulation assembly like ImageSharp or Skia. You only have to add the needed bindings package via nuget and add a "using <namespace>" to your code.
https://www.nuget.org/packages?q=ZXing.Net.Bindings

**Comment by oduis** [comment]
Thanks Michael, works like a charm.
