### ISSUE TITLE
Release 0.16.7 is broken for target net6.0?

### ISSUE THREAD

**Issue by EPinci** [micjahn/ZXing.Net#379]
Hello, looks like there's something broken in release 0.16.7 with a net6.0 target.

This declaration, that used to work in 0.16.6:
`var decoder = new BarcodeReader()`
now complains that there's no constructor with zero parameters.
That constructor still appears to be in the code (?).

**Comment by GF-Huang** [comment]
They are making a breaking change!!! 

![image](https://user-images.githubusercontent.com/4510984/147610143-40ecf320-6168-4564-adaf-f8a9c589508b.png)

**Comment by EPinci** [comment]
Uhm, na, it doesn't make sense to make such a breaking change in a patch release.
Furthermore, at least for my case, the code for the parameterless constructor seems to be still there (https://github.com/micjahn/ZXing.Net/blob/master/Source/lib/BarcodeReader.Bitmap.cs).
Seems something is wrong in the release...

**Comment by micjahn** [comment]
It isn't really a breaking change and there is nothing wrong with that release.
Before 0.16.7 ZXing.Net doesn't support .Net 6. Every time, when the nuget package was used with a .Net 6 project, the .Net Coreapp 3.1 assembly was used under the hood. The .Net Coreapp 3.1 version is built with direct support for System.Drawing.
But it isn't usable in a non-windows environment.
ZXing.Net 0.16.7 contains an assembly that is built against .Net 6.0.
But that version doesn't contain the bitmap support. That is necessary because otherwise the assembly can't be used
on platforms which doesn't support System.Drawing (f.e. WASM/Webassembly).
If you now upgrade from 0.16.6 to 0.16.7 nuget chooses the .Net 6.0 version of ZXing.net instead of the .Net Coreapp 3.1 version.

The System.Drawing-related parts are now in a separate package which contains the missing classes with the parameterless constructor.
Please use the following nuget package:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/

Additionally, now you have the option to use ZXing.Net for .Net 6.0 with System.Drawing or every other supported image manipulation assembly like ImageSharp or Skia. You only have to add the needed bindings package via nuget and add a "using " to your code.
https://www.nuget.org/packages?q=ZXing.Net.Bindings

**Comment by GF-Huang** [comment]
So, where's the `BarcodeWriter` (no T) gone?

**Comment by micjahn** [comment]
The nuget package ZXing.Net.Bindings.Windows.Compatibility was updated to version 0.16.10. That version contains the missing classes.
Btw. you can use the class BarcodeWriterGeometry directly.
```
private readonly ZXing.Windows.Compatibility.BarcodeWriterGeometry _writer = new() {...}
...
return _writer.Write(text);
...
```
It saves a small amoung of ressources because the renderer instance isn't create every call.
