### ISSUE TITLE
BitmapLuminanceSource not available in .Net 6

### ISSUE THREAD

**Issue by DavidPressman** [micjahn/ZXing.Net#383]
The BitmapLuminanceSource class is not available in .Net 6.

**Comment by micjahn** [comment]
Please add the following package to your project:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/

The BitmapLuminanceSource, BarcodeReader and other classes are in the namespace ZXing.Windows.Compatibility.
The core ZXing.Net package doesn't include the windows bitmap specific classes, so that it can be used in other environments like WebAssembly, etc.

**Comment by DavidPressman** [comment]
Thank you for a quick answer that did indeed solve my problem.

David Pressman

________________________________
