### ISSUE TITLE
Doc for 0.16.8 ?

### ISSUE THREAD

**Issue by anthonyChaussin-d4e** [micjahn/ZXing.Net#413]
Hello, I trying to figure out how to use the new version in c#.

The documentation seems outdated  because I have an error in the first line of code

```c#
// create a barcode reader instance
var reader = new BarcodeReader();
```
which gives me ```Erreur	CS0305	L'utilisation du type générique 'BarcodeReader<T>' nécessite des arguments de type 1```

Could someone please help me find where I am wrong ?

**Comment by micjahn** [comment]
Please add one of the binding packages to your project:
https://www.nuget.org/packages?q=ZXing.Bindings
Since .Net Standard there isn't a default BarcodeReader implementation for a specific image library in the base package included. It's because the System.Drawing.Bitmap classes are missing in .Net Standard. In .Net 5 and 6 the same.
So all the specific implementations for image manipulation libraries are separated into binding packages.
If you are not sure which one you should use you can start with the following:
https://www.nuget.org/packages/ZXing.Net.Bindings.Windows.Compatibility/
