### ISSUE TITLE
Zxing.Net issue with few barcode images

### ISSUE THREAD

**Issue by madhuinfos** [micjahn/ZXing.Net#43]
Hi,

![dg2138ey](https://user-images.githubusercontent.com/11314924/30782368-c3a8db7a-a14e-11e7-9139-8e5b6f8f3710.JPG)

Im using Zxing.Net for Bar code detection. Most of the cases its working fine. But for few images im facing an issue when the barcode is rotated. I have attached the sample bar code image for reference.
Im using the zxing library with below options,

this.reader = new BarcodeReader()
            {
                AutoRotate = true,

                Options = new DecodingOptions()
                {
                    TryHarder = true,
                    PossibleFormats = new List<BarcodeFormat>
                    {
                        BarcodeFormat.EAN_8
                    },
                },
                TryInverted = true
            };
Please suggest how can the accuracy can be improved with different rotations of attached images. 
Note: I cant stop the rotation as user captures the print out of bar code image.

**Comment by micjahn** [comment]
I do not know why it does not work for you. I tried it with the WinFormsDemo and it could be scanned without issues. The WinFormsDemo uses the same options. On the other hand there are no more options which you can use. Sometimes it gives better results if the GlobalHistogramBinarizer is used instead of the HybridBinarizer.
The original java based online decoder works, too:
https://zxing.org/w/decode?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F11314924%2F30782368-c3a8db7a-a14e-11e7-9139-8e5b6f8f3710.JPG
