### ISSUE TITLE
Constructor no more working

### ISSUE THREAD

**Issue by myCollections** [micjahn/ZXing.Net#473]
Hello,

Since i update to latest nuget package default constructor is no more working :

` BarcodeReader reader = new BarcodeReader();`

I got this error message :

_Using the generic type 'BarcodeReader<T>' requires 1 type arguments_

Any clue on this ?

Thanks a lot for your help

Regards

**Comment by micjahn** [comment]
Please try the solution which is described here:
https://stackoverflow.com/questions/74797869/zxing-net-0-16-8-barcodereaderbitmap-and-bitmapluminancesource-initialisation/74821044?r=SearchResults&s=4%7C0.0000#74821044
________________________________
Von: myCollections ***@***.***>
Gesendet: Thursday, December 22, 2022 7:54:13 PM
An: micjahn/ZXing.Net ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [micjahn/ZXing.Net] Constructor no more working (Issue #473)


Hello,

Since i update to latest nuget package default constructor is no more working :

BarcodeReader reader = new BarcodeReader();

I got this error message :

Using the generic type 'BarcodeReader' requires 1 type arguments

Any clue on this ?

Thanks a lot for your help

Regards

**Comment by myCollections** [comment]
Hi, It works fine thanks a lot for your help.

Regards.
