### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by vdiddlodka** [micjahn/ZXing.Net#498]
We are considering switching to this library from our current obsoleted third party package. Is there any concerns over long term support due to the Zxing project being [Maintenance Mode Only](https://github.com/zxing/zxing#project-in-maintenance-mode-only) ?

**Comment by micjahn** [comment]
That is one of the important questions if somebody decides to use an open-source product. I maintain this project (ZXing.Net, the C# port of the original java-based zxing library!) for more than 10 years now. I can not guarantee that I will do it for the rest of my life. It costs me a lot of my spare free time. Feel free to use it as-is. And because it is open source you can also fix issues by yourself.

**Comment by vdiddlodka** [comment]
I completely understand and appreciate the response. Thanks for the time you have already given and helping the community!
