### ISSUE TITLE
How to improve recognition rate if the barcode is too small?

### ISSUE THREAD

**Issue by simphonydeveloper** [micjahn/ZXing.Net#516]
Currently, I use OpenCv+Zxing to read the content of barcodes. When the barcode is very small, the recognition rate is very low, about 2-3cm. Is there any way to improve recognition speed?
Best regards.
Thank you.

**Comment by micjahn** [comment]
Can you provide a code snippet that shows how you use ZXing.Net?
And a sample image that isn't recognized would be helpful.

**Comment by simphonydeveloper** [comment]
Thanks for your reply, here is the test code.
https://github.com/simphonydeveloper/OpenCvZxingTest

**Comment by micjahn** [comment]
I try to decode both images in your repo.
The image "2.jpg" could be decoded out-of-the-box without any problems. The image "1.jpg" isn't too small, it is way too much rotated. ZXing.Net cannot successfully decode barcodes from every angle.

**Comment by simphonydeveloper** [comment]
I will try my best to encourage customers to identify in a suitable way, but if they do so through video, the effect will be worse. Is there any way to improve it currently?

**Comment by micjahn** [comment]
Nothing really useful within the ZXing.Net assembly. Perhaps you can use some other libraries like OpenCV to preprocess the image before decoding. But I don't have any experience with it.

**Comment by rob313663** [comment]
The code is a Code 39 without a check character. With a Zebra TC52 Android device (the barcode reader is a 2D imager) it can be read from my screen without any problems in any rotation. So the code itself is a perfectly valid Code 39, but as micjahn said, the rotation is the problem.

The text under the barcode contains "SKU", it is not part of the code. The text under the barcode should be *11145097*.

![code39](https://github.com/micjahn/ZXing.Net/assets/23123057/cf34bae9-aca2-4de6-bba4-66d26fa8e747)

**Comment by rob313663** [comment]
I am sorry, my previous comment was wrong, I analyzed the wrong picture.

The 1.jpg, when rotated -72.5 degrees get like this:

![image](https://github.com/micjahn/ZXing.Net/assets/23123057/409a123e-d50c-415c-b065-2fa2a5446439)

Not very good quality but it can be read with ZXing if rotated first. The same code in any rotation can be read by Zebra TC52, an Android device with built in 2D imager reading barcodes in "hardware".

If I understand ZXing.Result.RawBytes correctly, its contents is:

[STARTC][FNC1][11][14][88][26][CODEA][NUL][SPACE][STOP]

Code 128 barcodes that has FNC1 as its first character should follow the GS1 standard.

<img width="539" alt="image" src="https://github.com/micjahn/ZXing.Net/assets/23123057/a0de321d-d3b6-4346-8188-882aa4dee32c">

If the code was a GS1-128 code, then [11] would be an application identifier saying the data is Production Date, and 148826 should be a date in the format YYMMDD but it clearly isn't.

And then at the end of the barcode there is a NUL character, and possibly a space too (I dunno if ZXing includes the check code word at the end in RawBytes).

So my conclusion is, it is good that you can't read that barcode because it has so many problems and violates the GS1 standard.

/rob

**Comment by micjahn** [comment]
Is there anything left to do here or can the issue be closed?
