### ISSUE TITLE
A small log bug

### ISSUE THREAD

**Issue by tohidemyname** [micjahn/ZXing.Net#538]
crossCheckVertical(int,int,int,int)@FinderPatternFinder has the following code:

private float? crossCheckHorizontal(int startJ, int centerI, int maxCount, int originalStateCountTotal)
        {...
     if (j < 0 || stateCount[1] > maxCount)
            {
                return null;
            }
...
}

The above code can be ported from zxing, but zxing has fixed a bug in the above code. The commit is:
https://github.com/zxing/zxing/commit/3fd38e3893f58a0283dd45299d5cdaa7d5404f46

Here, the patch is as follows:

 - if (i < 0 || stateCount[0] > maxCount) {
  +  if (stateCount[0] > maxCount) {
      return Float.NaN;
    }

**Comment by micjahn** [comment]
I double-checked the current C# code of the methods crossCheckHorizontal and crossCheckVertical against the current java version but I didn't find any difference. Currently, it seems to me that the code changes of the commit which you mentioned were rolled back later. But I'm not sure. Anyway, I don't know why I should change it if the code looks the same. 
Which error would be fixed with that patch? Do you have a repro for an error or something similar?
